- Added stub for ceph driver - Modified diego.yml to include tags for spiff merging the voldrivers - Modified scripts for manifest generation to include an optional driver colocated with the cell   [#112362783](https://www.pivotaltracker.com/story/show/112362783)
Signed-off-by: Nagapramod Mandagere <pramod@us.ibm.com>
Signed-off-by: Julian Hjortshoj <julian.hjortshoj@emc.com>

diff --git a/scripts/generate-deployment-manifest b/scripts/generate-deployment-manifest
--- a/scripts/generate-deployment-manifest
+++ b/scripts/generate-deployment-manifest
@@ -21,6 +21,7 @@ OPTIONAL ARGUMENTS:
     -n <count-path>     Path to instance-count-overrides stub file.
     -v <versions-path>  Path to release-versions stub file.
     -s <sql-db-path>    Path to SQL stub file.
+    -d <voldriver-path> Path to voldriver stub file.
     -g                  Opt into using guardian-release for cells.
 
 EXAMPLE:
@@ -31,6 +32,7 @@ EXAMPLE:
       -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
       -v manifest-generation/bosh-lite-stubs/release-versions.yml \\
       -s manifest-generation/bosh-lite-stubs/diego-sql.yml \\
+      -d manifest-generation/bosh-lite-stubs/experimental/voldriver/drivers.yml \\
       -r \\
       -g
 EOF
@@ -40,7 +42,7 @@ EOF
 base_releases="${manifest_generation}/base-releases.yml"
 garden_properties=""
 
-while getopts "c:i:p:n:k:v:s:rbg" opt; do
+while getopts "c:i:p:n:k:v:s:d:rbg" opt; do
   case $opt in
     c)
       cf_deployment_manifest=$OPTARG
@@ -71,6 +73,9 @@ while getopts "c:i:p:n:k:v:s:rbg" opt; do
       ;;
     s)
       sql_settings=$OPTARG
+      ;;
+    d)
+      voldriver_settings=$OPTARG
       ;;
     *)
       echo "Unknown arguments"
@@ -115,6 +120,11 @@ if [[ ! -z "${sql_settings}" && ! -f "${sql_settings}" ]]; then
   argument_error=true
 fi
 
+if [[ ! -z "${voldriver_settings}" && ! -f "${voldriver_settings}" ]]; then
+  >&2 echo "ERROR: Voldriver Setting stub '${voldriver_settings}' is not a regular file"
+  argument_error=true
+fi
+
 if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
   >&2 echo "ERROR: Instance-count-overrides stub '${instance_counts}' is not a regular file"
   argument_error=true
@@ -145,6 +155,7 @@ spiff merge \
   ${property_overrides} \
   ${instance_counts} \
   ${sql_settings} \
+  ${voldriver_settings} \
   ${iaas_settings} \
   ${tmpdir}/config-from-cf.yml \
   > ${tmpdir}/diego.yml
